# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Baosen Zhang
email: zhangbao@uw.edu
description: > # this means to ignore newlines until "baseurl:"
  Baosen Zhang is an Assistant Professor in the Electrical Engineering Department at the University of Washington. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://faculty.washington.edu/zhangbao/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
scholar:
  style: ./_bibliography/ieee-with-url.csl
  locale: en

  sort_by: year
  order: descending

  group_by: none
  group_order: ascending

  source: ./_bibliography
  bibliography: pubs.bib
  bibliography_template: bibtemplate

  replace_strings: true

  use_raw_bibtex_entry: false

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

# Other options
permalink: blog/:year/:month/:title

